name: Test and Validate

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ~12.16.3
      uses: actions/setup-node@v1
      with:
        node-version: '~12.16.3'
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: yarn lint
    - name: Validate react-native-libraries.json
      run: yarn data:validate
    - name: Test react-native-libraries.json
      run: yarn data:test
